### ISSUE TITLE
Python 2 syntax error in merge_overlapping_intervals.py

### ISSUE THREAD

**Issue by cclauss** [ealter/vim_turing_machine#3]
flake8 testing of https://github.com/ealter/vim_turing_machine on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./vim_turing_machine/machines/merge_overlapping_intervals/merge_overlapping_intervals.py:343:17: E999 SyntaxError: invalid syntax
                *self.move_to_blank_spaces(
                ^
```

**Comment by ealter** [comment]
Thanks for the bug report! I wrote this to be compatible with python 3, but not python 2. The test suite currently uses pre-commit to run flake8 on all of the code with python 3.6.

I think for now I'll leave this as python3 only since then we can use convenient syntax like the one you found here, but I'm open to suggestions if you think python2 compatibility would make this repository more useful.

**Comment by ealter** [comment]
If we don't end up supporting python2, then I'll at least make a note of that in the readme :)

**Comment by cclauss** [comment]
Personally, I think it is OK to drop Py2 support (as long as it is documented).
https://github.com/ealter/vim_turing_machine/blob/master/setup.py#L10

**Comment by ealter** [comment]
Good catch in the setup.py! I used a package generator to scaffold this repository which defaults to supporting python2 and python3. Do you think I should say anything in the readme or just document this in the setup.py classifiers?

**Comment by cclauss** [comment]
Both in readme (for humans) and setup (for machines).  ;-)
